### ISSUE TITLE
Bug: Missing Parameter in setSession

### ISSUE THREAD

**Issue by MamadouAlySy** [TheCodingWorkshop/MagmaSkeleton#2]
there is a missing parameter in **_MagmaSkeleton/Public/index.php on line 34._**
I thinks it should receive _**Yaml::file('session')**_ as parameter

**Comment by TheCodingWorkshop** [comment]
the parameter is optional. As there are internal settings for the session component which is applied automatically if no parameter is defined. But the session.yml should be located within the config directory

**Comment by MamadouAlySy** [comment]
thank you very much i watched your videos and you did a very good job.
I tried without passing any parameter it displays an error, I even tried by passing it the configuration but other error appears.
the project is dependent on MagmacCore do you think MagmaCore is up to date on pakagist?

**Comment by TheCodingWorkshop** [comment]
Sorry about It is updated now

**Comment by TheCodingWorkshop** [comment]
Thanks for supporting the channel. But can I ask what package you are using. Are you using the MagmaSkeleton or Just the MagmaCore from youtube

**Comment by MamadouAlySy** [comment]
Im using the MagmaCore From youtube for learning.
For MagmaSkeleton i tried intalling it but does'nt work for me that's why i reported issues

**Comment by TheCodingWorkshop** [comment]
What's your setup environment

**Comment by MamadouAlySy** [comment]
I'm in Pop OS 20.10 and im using php8.0 docker container with apache2 and mysql5.7

**Comment by TheCodingWorkshop** [comment]
Can you send me a screen shot of that error you got. I would appreciate that. Send it to riccodingworkshop@gmail.com

**Comment by MamadouAlySy** [comment]
ok i sent it to you
